### ISSUE TITLE
Update to 1.9.4

### ISSUE THREAD

**Issue by lizardfreak321** [mrockey28/ItemRepair#2]
[ItemRepair.zip](https://github.com/mrockey28/ItemRepair/files/276060/ItemRepair.zip)
I did it for you! I also added compatibility with very high damage values, and I also changed the code to fix issues with about 40 instances of depreciated code being used. I would love it if you gave me credit or added me to the project, but you do not need to.

**Comment by lizardfreak321** [comment]
[itemrepairjar.zip](https://github.com/mrockey28/ItemRepair/files/276061/itemrepairjar.zip)
Here is the compiled jar if you want to test it or if anyone looking at this wants it.

**Comment by mrockey28** [comment]
Fantastic! Thanks a bunch! I've added you as a contributor, you should now be able to push and pull to the project. I've also integrated your changes (with credit to you) and uploaded your .jar to Bukkit-dev (http://dev.bukkit.org/bukkit-plugins/autorepair/). Thanks again.
